# Generated by Django 3.2.4 on 2021-07-19 12:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('totalCost', models.FloatField()),
                ('amountPaid', models.FloatField()),
                ('balance', models.FloatField()),
                ('completed', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price', models.FloatField(default=1)),
                ('Buy_price', models.FloatField(default=1)),
                ('image', models.ImageField(upload_to='')),
                ('qty_in_store', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockmgmt.category')),
            ],
        ),
        migrations.CreateModel(
            name='Ordereditems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField(default=0)),
                ('profit', models.FloatField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockmgmt.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockmgmt.product')),
            ],
        ),
    ]
